set -g @thm_bg "#040c22"
set -g @thm_bg2 "#0d1a3a"
set -g @thm_bg4 "#203463"
set -g @thm_fg "#eaf0fb"
set -g @thm_gray "#818daa"
set -g @thm_accent "#1f58eb"
set -g @thm_yellow "#f2c45e"
set -g @thm_aqua "#4aa6f0"
set -g status-style "bg=default,fg=#eaf0fb"
set -g pane-active-border-style "fg=#1f58eb,bg=default"
set -g pane-border-style "fg=#203463,bg=default"
