set -g @thm_bg "#0a0e1a"
set -g @thm_bg2 "#131a2e"
set -g @thm_bg4 "#273253"
set -g @thm_fg "#eef0f6"
set -g @thm_gray "#828aa0"
set -g @thm_accent "#fddf00"
set -g @thm_yellow "#fddf00"
set -g @thm_aqua "#2f5fb0"
set -g status-style "bg=default,fg=#eef0f6"
set -g pane-active-border-style "fg=#fddf00,bg=default"
set -g pane-border-style "fg=#273253,bg=default"
