set -g @thm_bg "#070d1f"
set -g @thm_bg2 "#101a36"
set -g @thm_bg4 "#213363"
set -g @thm_fg "#eef1f8"
set -g @thm_gray "#808ca8"
set -g @thm_accent "#fc3d21"
set -g @thm_yellow "#f0c44e"
set -g @thm_aqua "#3f7fe0"
set -g status-style "bg=default,fg=#eef1f8"
set -g pane-active-border-style "fg=#fc3d21,bg=default"
set -g pane-border-style "fg=#213363,bg=default"
