set -g @thm_bg "#0a0a0a"
set -g @thm_bg2 "#1c1c1c"
set -g @thm_bg4 "#313131"
set -g @thm_fg "#eaeaea"
set -g @thm_gray "#8a8a8a"
set -g @thm_accent "#ff5a2c"
set -g @thm_yellow "#f5b942"
set -g @thm_aqua "#2dd4bf"
set -g status-style "bg=default,fg=#eaeaea"
set -g pane-active-border-style "fg=#ff5a2c,bg=default"
set -g pane-border-style "fg=#313131,bg=default"
