set -g @thm_bg "#050608"
set -g @thm_bg2 "#0d1116"
set -g @thm_bg4 "#1b2430"
set -g @thm_fg "#e7f6f3"
set -g @thm_gray "#6f8a86"
set -g @thm_accent "#00cdc5"
set -g @thm_yellow "#e9c46a"
set -g @thm_aqua "#d81b6e"
set -g status-style "bg=default,fg=#e7f6f3"
set -g pane-active-border-style "fg=#00cdc5,bg=default"
set -g pane-border-style "fg=#1b2430,bg=default"
