set -g @thm_bg "#0d1211"
set -g @thm_bg2 "#15201d"
set -g @thm_bg4 "#273631"
set -g @thm_fg "#e6efec"
set -g @thm_gray "#7c8b87"
set -g @thm_accent "#46c2b4"
set -g @thm_yellow "#e8c477"
set -g @thm_aqua "#ec4a2c"
set -g status-style "bg=default,fg=#e6efec"
set -g pane-active-border-style "fg=#46c2b4,bg=default"
set -g pane-border-style "fg=#273631,bg=default"
