set -g @thm_bg "#1e1e2e"
set -g @thm_bg2 "#313244"
set -g @thm_bg4 "#585b70"
set -g @thm_fg "#cdd6f4"
set -g @thm_gray "#6c7086"
set -g @thm_accent "#89b4fa"
set -g @thm_yellow "#f9e2af"
set -g @thm_aqua "#94e2d5"
set -g status-style "bg=default,fg=#cdd6f4"
set -g pane-active-border-style "fg=#89b4fa,bg=default"
set -g pane-border-style "fg=#585b70,bg=default"
