set -g @thm_bg "#001e40"
set -g @thm_bg2 "#08305a"
set -g @thm_bg4 "#134d80"
set -g @thm_fg "#eaf1f8"
set -g @thm_gray "#7d93ad"
set -g @thm_accent "#0a6cb0"
set -g @thm_yellow "#f0b84a"
set -g @thm_aqua "#e4002b"
set -g status-style "bg=default,fg=#eaf1f8"
set -g pane-active-border-style "fg=#0a6cb0,bg=default"
set -g pane-border-style "fg=#134d80,bg=default"
