set -g @thm_bg "#0a0b0e"
set -g @thm_bg2 "#14161d"
set -g @thm_bg4 "#262a38"
set -g @thm_fg "#eef0f4"
set -g @thm_gray "#7d8290"
set -g @thm_accent "#d21f2d"
set -g @thm_yellow "#ffc20e"
set -g @thm_aqua "#ffc20e"
set -g status-style "bg=default,fg=#eef0f4"
set -g pane-active-border-style "fg=#d21f2d,bg=default"
set -g pane-border-style "fg=#262a38,bg=default"
