set -g @thm_bg "#131313"
set -g @thm_bg2 "#1f1d1b"
set -g @thm_bg4 "#342c27"
set -g @thm_fg "#f1ece9"
set -g @thm_gray "#8d8580"
set -g @thm_accent "#fa582d"
set -g @thm_yellow "#f5b14a"
set -g @thm_aqua "#3b78ff"
set -g status-style "bg=default,fg=#f1ece9"
set -g pane-active-border-style "fg=#fa582d,bg=default"
set -g pane-border-style "fg=#342c27,bg=default"
