set -g @thm_bg "#0e172d"
set -g @thm_bg2 "#182240"
set -g @thm_bg4 "#2c3a60"
set -g @thm_fg "#eaeef6"
set -g @thm_gray "#828ba6"
set -g @thm_accent "#5b95d6"
set -g @thm_yellow "#d8b878"
set -g @thm_aqua "#c8a667"
set -g status-style "bg=default,fg=#eaeef6"
set -g pane-active-border-style "fg=#5b95d6,bg=default"
set -g pane-border-style "fg=#2c3a60,bg=default"
