set -g @thm_bg "#1d2021"
set -g @thm_bg2 "#32302f"
set -g @thm_bg4 "#504945"
set -g @thm_fg "#d4be98"
set -g @thm_gray "#928374"
set -g @thm_accent "#7daea3"
set -g @thm_yellow "#d8a657"
set -g @thm_aqua "#89b482"
set -g status-style "bg=default,fg=#d4be98"
set -g pane-active-border-style "fg=#7daea3,bg=default"
set -g pane-border-style "fg=#504945,bg=default"
