set -g @thm_bg "#08090f"
set -g @thm_bg2 "#12141d"
set -g @thm_bg4 "#272b3a"
set -g @thm_fg "#eef0f6"
set -g @thm_gray "#767d8e"
set -g @thm_accent "#c3ccd9"
set -g @thm_yellow "#e8cf8a"
set -g @thm_aqua "#5b8fc9"
set -g status-style "bg=default,fg=#eef0f6"
set -g pane-active-border-style "fg=#c3ccd9,bg=default"
set -g pane-border-style "fg=#272b3a,bg=default"
