set -g @thm_bg "#0e1626"
set -g @thm_bg2 "#19243b"
set -g @thm_bg4 "#314465"
set -g @thm_fg "#e7ecf4"
set -g @thm_gray "#8190a8"
set -g @thm_accent "#d23b50"
set -g @thm_yellow "#f0c674"
set -g @thm_aqua "#5fb0d0"
set -g status-style "bg=default,fg=#e7ecf4"
set -g pane-active-border-style "fg=#d23b50,bg=default"
set -g pane-border-style "fg=#314465,bg=default"
