set -g @thm_bg "#121212"
set -g @thm_bg2 "#262626"
set -g @thm_bg4 "#3a3a3a"
set -g @thm_fg "#dedede"
set -g @thm_gray "#929292"
set -g @thm_accent "#97bedc"
set -g @thm_yellow "#ffba7b"
set -g @thm_aqua "#1ab2a8"
set -g status-style "bg=default,fg=#dedede"
set -g pane-active-border-style "fg=#97bedc,bg=default"
set -g pane-border-style "fg=#3a3a3a,bg=default"
