set -g @thm_bg "#0c2840"
set -g @thm_bg2 "#153854"
set -g @thm_bg4 "#265a82"
set -g @thm_fg "#eaf1f7"
set -g @thm_gray "#7e93a6"
set -g @thm_accent "#2f86bd"
set -g @thm_yellow "#fecf5e"
set -g @thm_aqua "#fecf5e"
set -g status-style "bg=default,fg=#eaf1f7"
set -g pane-active-border-style "fg=#2f86bd,bg=default"
set -g pane-border-style "fg=#265a82,bg=default"
