set -g @thm_bg "#0a0e12"
set -g @thm_bg2 "#131922"
set -g @thm_bg4 "#273340"
set -g @thm_fg "#e8f0ea"
set -g @thm_gray "#7d8a87"
set -g @thm_accent "#86c232"
set -g @thm_yellow "#d8c45a"
set -g @thm_aqua "#2f86d0"
set -g status-style "bg=default,fg=#e8f0ea"
set -g pane-active-border-style "fg=#86c232,bg=default"
set -g pane-border-style "fg=#273340,bg=default"
