set -g @thm_bg "#0a0c07"
set -g @thm_bg2 "#161a0e"
set -g @thm_bg4 "#2c331b"
set -g @thm_fg "#eef3e2"
set -g @thm_gray "#8f9b78"
set -g @thm_accent "#c4f000"
set -g @thm_yellow "#e6e84a"
set -g @thm_aqua "#7fd6a8"
set -g status-style "bg=default,fg=#eef3e2"
set -g pane-active-border-style "fg=#c4f000,bg=default"
set -g pane-border-style "fg=#2c331b,bg=default"
