set -g @thm_bg "#091019"
set -g @thm_bg2 "#121c2e"
set -g @thm_bg4 "#25324e"
set -g @thm_fg "#e8ecf6"
set -g @thm_gray "#7e8aa3"
set -g @thm_accent "#e21f40"
set -g @thm_yellow "#f3c66b"
set -g @thm_aqua "#50e6e3"
set -g status-style "bg=default,fg=#e8ecf6"
set -g pane-active-border-style "fg=#e21f40,bg=default"
set -g pane-border-style "fg=#25324e,bg=default"
