set -g @thm_bg "#01202c"
set -g @thm_bg2 "#07303f"
set -g @thm_bg4 "#124b60"
set -g @thm_fg "#eaf2f5"
set -g @thm_gray "#7d96a0"
set -g @thm_accent "#e8b00f"
set -g @thm_yellow "#e8b00f"
set -g @thm_aqua "#2f9fc9"
set -g status-style "bg=default,fg=#eaf2f5"
set -g pane-active-border-style "fg=#e8b00f,bg=default"
set -g pane-border-style "fg=#124b60,bg=default"
