set -g @thm_bg "#0a1428"
set -g @thm_bg2 "#13213e"
set -g @thm_bg4 "#263a66"
set -g @thm_fg "#eaeef7"
set -g @thm_gray "#808ca6"
set -g @thm_accent "#3a63c4"
set -g @thm_yellow "#e8b84a"
set -g @thm_aqua "#b81f33"
set -g status-style "bg=default,fg=#eaeef7"
set -g pane-active-border-style "fg=#3a63c4,bg=default"
set -g pane-border-style "fg=#263a66,bg=default"
