set -g @thm_bg "#0a0a09"
set -g @thm_bg2 "#161510"
set -g @thm_bg4 "#2a2718"
set -g @thm_fg "#f0ece0"
set -g @thm_gray "#8a8676"
set -g @thm_accent "#ffcc01"
set -g @thm_yellow "#ffcc01"
set -g @thm_aqua "#e0b020"
set -g status-style "bg=default,fg=#f0ece0"
set -g pane-active-border-style "fg=#ffcc01,bg=default"
set -g pane-border-style "fg=#2a2718,bg=default"
