set -g @thm_bg "#120c06"
set -g @thm_bg2 "#231910"
set -g @thm_bg4 "#43301c"
set -g @thm_fg "#f3ebe1"
set -g @thm_gray "#a18f7c"
set -g @thm_accent "#f58220"
set -g @thm_yellow "#f7c14a"
set -g @thm_aqua "#3fc4b0"
set -g status-style "bg=default,fg=#f3ebe1"
set -g pane-active-border-style "fg=#f58220,bg=default"
set -g pane-border-style "fg=#43301c,bg=default"
