set -g @thm_bg "#121417"
set -g @thm_bg2 "#1e2227"
set -g @thm_bg4 "#39414a"
set -g @thm_fg "#eef0f2"
set -g @thm_gray "#8a929c"
set -g @thm_accent "#f7941e"
set -g @thm_yellow "#f7c14a"
set -g @thm_aqua "#3fc4b0"
set -g status-style "bg=default,fg=#eef0f2"
set -g pane-active-border-style "fg=#f7941e,bg=default"
set -g pane-border-style "fg=#39414a,bg=default"
