set -g @thm_bg "#1a1b26"
set -g @thm_bg2 "#24283b"
set -g @thm_bg4 "#414868"
set -g @thm_fg "#c0caf5"
set -g @thm_gray "#565f89"
set -g @thm_accent "#7aa2f7"
set -g @thm_yellow "#e0af68"
set -g @thm_aqua "#7dcfff"
set -g status-style "bg=default,fg=#c0caf5"
set -g pane-active-border-style "fg=#7aa2f7,bg=default"
set -g pane-border-style "fg=#414868,bg=default"
