set -g @thm_bg "#140b0c"
set -g @thm_bg2 "#251516"
set -g @thm_bg4 "#46282a"
set -g @thm_fg "#f3e6e6"
set -g @thm_gray "#a3898a"
set -g @thm_accent "#e03a4e"
set -g @thm_yellow "#f5c462"
set -g @thm_aqua "#3fc4c4"
set -g status-style "bg=default,fg=#f3e6e6"
set -g pane-active-border-style "fg=#e03a4e,bg=default"
set -g pane-border-style "fg=#46282a,bg=default"
